<?php

$planes = array ( 'temp' => array('Tempest', 'eng'),
				  'spit16' => array('Spitfire Mk.XVI', 'eng'),
				  'spit14' => array('Spitfire Mk.XIV', 'eng'),
				  '109k4' => array('Bf 109K-4', 'ger'),
				  'la7' => array('La-7', 'rus'),
				  '109g14' => array('Bf 109G-14', 'ger'),
				  'spit8' => array('Spitfire Mk.VIII', 'eng'),
				  'la5fn' => array('La-5FN', 'rus'),
				  'f4u4' => array('F4U-4', 'usa'),
				  '190d9' => array('Fw 190D-9', 'ger'),
				  'ki84' => array('Ki-84', 'jap'),
				  '109g2' => array('Bf 109G-2', 'ger'),
				  'n1k2j' => array('N1K2-J', 'jap'),
				  '109f4' => array('Bf 109F-4', 'ger'),
				  '109g6' => array('Bf 109G-6', 'ger'),
				  'p38j' => array('P-38J', 'usa'),
				  'yak9u' => array('Yak-9U', 'rus'),
				  'p38l' => array('P-38L', 'usa'),
				  'c205' => array('C.205', 'ita'),
				  'ta152h' => array('Ta 152H', 'ger'),
				  'typh' => array('Typhoon', 'eng'),
				  '190a5' => array('Fw 190A-5', 'ger'),
				  'f4u1d' => array('F4U-1D', 'usa'),
				  'spit9' => array('Spitfire Mk.IX', 'eng'),
				  '190a8' => array('Fw 190A-8', 'ger'),
				  'p51d' => array('P-51D', 'usa'),
				  'f4u1c' => array('F4U-1C', 'usa'),
				  '190f8' => array('Fw 190F-8', 'ger'),
				  'f6f5' => array('F6F-5', 'usa'),
				  'p47n' => array('P-47N', 'usa'),
				  'p47d40' => array('P-47D-40', 'usa'),
				  'p51b' => array('P-51B', 'usa'),
				  'c202' => array('C.202', 'ita'),
				  'mosq' => array('Mosquito', 'eng'),
				  'p38g' => array('P-38G', 'usa'),
				  'p47d25' => array('P-47D-25', 'usa'),
				  'f4u1' => array('F4U-1', 'usa'),
				  'p47d11' => array('P-47D-11', 'usa'),
				  'spit1' => array('Spitfire Mk.I', 'eng'),
				  'spit5' => array('Spitfire Mk.V', 'eng'),
				  'yak9t' => array('Yak-9T', 'rus'),
				  'a6m5' => array('A6M5', 'jap'),
				  'fm2' => array('FM-2', 'usa'),
				  'ki61' => array('Ki-61', 'jap'),
				  '110g2' => array('Bf 110G-2', 'ger'),
				  'seaf2' => array('Seafire Mk.II', 'eng'),
				  'p40e' => array('P-40E', 'usa'),
				  '109e4' => array('Bf 109E-4', 'ger'),
				  'hurri2c' => array('Hurricane Mk.IIC', 'eng'),
				  '110c4b' => array('Bf 110C-4b', 'ger'),
				  'f4f4' => array('F4F-4', 'usa'),
				  'a6m2' => array('A6M2', 'jap'),
				  'hurri2d' => array('Hurricane Mk.IID', 'eng'),
				  'hurri1' => array('Hurricane Mk.I', 'eng'),
				  'p40b' => array('P-40B', 'usa')
				  );

$countries = array ('usa' => 'America',
					'eng' => 'Britain',
					'ger' => 'Germany',
					'rus' => 'Russia',
					'jap' => 'Japan',
					'ita' => 'Italy');
?>
